custom board
LISTENAI/docs-csk6 pull request #117
Opened 2022-07-26 09:11 UTC by qinxiaoqingct

2022-07-26 11:00 UTC, seasonyuu requested changes

2022-07-27 08:21 UTC, qinxiaoqingct commented on application/board.md
> +### 步骤四：修改dts和配置文件
dtsi去掉了，开发者不需要改这个文件

2022-07-27 10:22 UTC, seasonyuu requested changes

2022-07-27 10:22 UTC, seasonyuu commented on application/board.md
> +### 步骤四：修改dts和配置文件
dts 讲的时候，不要全篇都贴过来，只拿某个节点出来举例讲就好

2022-07-28 10:06 UTC, qinxiaoqingct commented on application/board.md
> +### 步骤四：修改dts和配置文件
距离wifi通道芯片说明修改的方法

2022-07-28 10:17 UTC, seasonyuu approved these changes

2022-07-28 10:17 UTC, merged